### ISSUE TITLE
Correspondence Matching Problem

### ISSUE THREAD

**Issue by Zhaohuanfeng** [Ji1Xingyu/lio_gvm#2]
Hi!
Very nice work! 
But the global covariance matrix in eq (9) of the paper is $^GC={^GR}{C}{^GT^T}$, should it be $^GC={^GR}{C}{^GR^T}$ ?

**Comment by Ji1Xingyu** [comment]
Thx for the correction! You are right it should be the rotation matrix. I'll modify it in the paper.

**Comment by Zhaohuanfeng** [comment]
In Incremental Global Map, Why $M=max(M, N)$ instead of $M=M+N$.

**Comment by Ji1Xingyu** [comment]
We wish to keep a constant update of the global map. 

Recalling the update weights, if we choose the M = M + N one, M within a voxel will increase without bounds and the future update in this voxel will not work. Instead, the M = max(M, N) scheme will bound M to be the max num of the LiDAR points within a voxel (e.g. the num when the voxel is very close to the LiDAR).

**Comment by Zhaohuanfeng** [comment]
Got it, thank you very much for your answer ！
