### ISSUE TITLE
Any new progress about the project?

### ISSUE THREAD

**Issue by chengwei0427** [Ji1Xingyu/lio_gvm#3]
Hi, @Ji1Xingyu 
Nice work, and any new progress about the project?

**Comment by Ji1Xingyu** [comment]
Hi Chenwei,

Sry for the late update, I got stuck at an ongoing project which result in little time for me to re-organize the code for lio-gvm... I will try my best to work on both the two projects and release lio-gvm within several weeks.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: chengwei ***@***.***>
发送时间: Wednesday, April 17, 2024 6:15:27 PM
收件人: Ji1Xingyu/lio_gvm ***@***.***>
抄送: #JI XINGYU# ***@***.***>; Mention ***@***.***>
主题: [Ji1Xingyu/lio_gvm] Any new progress about the project? (Issue #3)


Hi, @Ji1Xingyu<https://github.com/Ji1Xingyu>
Nice work, and any new progress about the project?

―

**Comment by a-github-learner** [comment]
Excellent work! May I ask if it is open source now? Your work has provided me with great inspiration, and it has had a profound impact on my current job. Thank you very much!

**Comment by Ji1Xingyu** [comment]
Hi Rocense, I'm glad to hear that my work had a good impact on your research, I promise that the code can be released by the end of May.

**Comment by Ji1Xingyu** [comment]
Hi all, the code has been packaged and sent to the project managers for review. It will be published once they have finished the process.

**Comment by chengwei0427** [comment]
Any news?

**Comment by a-github-learner** [comment]
Hows thing going？
