### ISSUE TITLE
A mathematical derivation question in your supplemental material pdf

### ISSUE THREAD

**Issue by zhongguanLiu** [Ji1Xingyu/lio_gvm#6]
In your eq(17), is the first item about the rotation part missing a rotation matrix from the IMU to the Global coordinate system?
![LIO-GVM](https://github.com/user-attachments/assets/8b9615d3-11c5-4515-ae89-2819b39dbae0)

**Comment by Ji1Xingyu** [comment]
Yeah you are correct, I might forget to add that term when editing. Will correct that in the arxiv paper. Thx!
